ARG BASE_IMAGE="saltydk/alpine-s6overlay:latest@sha256:cfe1b2fa2147455adb8d19be9ba00cdbbae71bfbcaa79bdcf230ff438afe5276"

FROM ${BASE_IMAGE}

ARG QBITTORRENT_REPOSITORY="userdocs/qbittorrent-nox-static-legacy"
ARG QBITTORRENT_RELEASE="release-4.3.9_v1.2.20"
ARG QBITTORRENT_UPSTREAM_REVISION="7"
ARG QBITTORRENT_REVISION="9"
ARG QBITTORRENT_SHA256_AMD64="edc96877d3727fa8da59e1331557c3528e78904ecc153fe02f05dcdc70c1e854"
ARG QBITTORRENT_SHA256_ARM64="14be50d941a17e2cde4e2466380f7b7db43e53fb0e58b5e9ba7f5ec89b4e9d52"
ARG TARGETARCH

LABEL maintainer="salty"

ENV \
  HOME="/config" \
  XDG_CONFIG_HOME="/config" \
  XDG_DATA_HOME="/config" \
  # 3 minutes for services to exit
  S6_SERVICES_GRACETIME=180000 \
  S6_KILL_GRACETIME=3000

# Install packages
RUN \
  echo "**** install packages for ${QBITTORRENT_RELEASE}-${QBITTORRENT_REVISION} ****" \
  && apk upgrade --no-cache \
  && apk add --no-cache \
    bind-tools \
    ca-certificates \
    curl \
    mediainfo \
    openssl \
    procps \
    tar \
    unzip \
    wget \
    zlib

RUN \
  case "${TARGETARCH}" in \
    "amd64") QBITTORRENT_ARCH="x86_64"; QBITTORRENT_SHA256="${QBITTORRENT_SHA256_AMD64}" ;; \
    "arm64") QBITTORRENT_ARCH="aarch64"; QBITTORRENT_SHA256="${QBITTORRENT_SHA256_ARM64}" ;; \
    *) echo "Unsupported architecture: ${TARGETARCH}" >&2; exit 1 ;; \
  esac \
  && echo "**** install qbittorrent-nox ****" \
  && curl -sSfL -o /usr/bin/qbittorrent-nox \
    "https://github.com/${QBITTORRENT_REPOSITORY}/releases/download/${QBITTORRENT_RELEASE}/${QBITTORRENT_ARCH}-qbittorrent-nox" \
  && echo "${QBITTORRENT_SHA256}  /usr/bin/qbittorrent-nox" | sha256sum -c - \
  && chmod 755 /usr/bin/qbittorrent-nox \
  && echo "**** cleanup ****" \
  && rm -rf \
    /root/.cache \
    /tmp/*

# Add root files
COPY ["root/", "/"]
COPY ["root-legacy/", "/"]

VOLUME ["/config", "/downloads"]
EXPOSE 8080/tcp
