#!/usr/bin/with-contenv bash

echo "Finishing qbittorrent!"
# Get PID
D_PID=`pidof qbittorrent-nox`

# Send kill signal
# kill -SIGINT ${D_PID} 2>/dev/null

# Wait for exit
while kill -0 ${D_PID} && ! [ $(ps -o stat --no-headers -p ${D_PID}) = "Zs" ] ; do
    echo "# $(date +%s) - PID ${D_PID} waiting for qbittorrent to quit"
    sleep 1
done
