#!/usr/bin/with-contenv bash

# Umask
UMASK_SET=${UMASK_SET:-022}
umask "${UMASK_SET}"

# Run
HOME=/config exec \
    s6-setuidgid abc \
        /usr/bin/qbittorrent-nox

# Sleep between restarts
sleep 1
