name: build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - '*.md'
    branches:
      - 'libtorrent1'

jobs:
  find-latest-version:
    runs-on: ubuntu-latest
    outputs:
      qbt-version: ${{ steps.set-latest-version.outputs.qbt-version }}
    steps:
      - uses: actions/checkout@v4
      - id: set-latest-version
        run: echo "qbt-version=$(head -6 Dockerfile | tail -1 | cut -d'"' -f2)" >> $GITHUB_OUTPUT

  docker:
    runs-on: ubuntu-latest
    needs: find-latest-version
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: saltydk/qbittorrent

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          sbom: true
          push: true
          tags: |
            saltydk/qbittorrent:${{ needs.find-latest-version.outputs.qbt-version }}
            saltydk/qbittorrent:latest
            saltydk/qbittorrent:libtorrent1
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
