name: update-check

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  find-latest-version:
    runs-on: ubuntu-latest
    outputs:
      qbt-version: ${{ steps.set-latest-version.outputs.qbt-version }}
    steps:
      - id: set-latest-version
        run: echo "::set-output name=qbt-version::$(curl https://api.github.com/repos/userdocs/qbittorrent-nox-static/releases/latest | jq -r '.tag_name')"

  update:
    runs-on: ubuntu-latest
    needs: find-latest-version
    steps:
      - name: Check Latest Release
        env:
          QBT_RELEASE_URL: ${{ needs.find-latest-version.outputs.qbt-version }}
        run: |
          echo $QBT_RELEASE_URL