name: version-check

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  find-latest-version:
    runs-on: ubuntu-latest
    outputs:
      qbt-version: ${{ steps.set-latest-version.outputs.qbt-version }}
    steps:
      - id: set-latest-version
        run: echo "::set-output name=qbt-version::$(curl -fsSL https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/dependency-version.json | jq -r '.qbittorrent')"

  find-latest-release:
    runs-on: ubuntu-latest
    needs: find-latest-version
    outputs:
      qbt-version: ${{ steps.set-latest-version.outputs.qbt-version }}
    steps:
      - id: set-latest-version
        run: echo "::set-output name=qbt-version::$(curl -fsSL "https://api.github.com/repos/userdocs/qbittorrent-nox-static/releases" | jq -r 'first(.[] | select(.tag_name | contains ("release-'"${{ needs.find-latest-version.outputs.qbt-version }}"_v2.'")) | .tag_name)')"

  find-latest-libtorrent1-release:
    runs-on: ubuntu-latest
    needs: find-latest-version
    outputs:
      qbt-libtorrent1-version: ${{ steps.set-latest-libtorrent1-version.outputs.qbt-libtorrent1-version }}
    steps:
      - id: set-latest-libtorrent1-version
        run: echo "::set-output name=qbt-libtorrent1-version::$(curl -fsSL "https://api.github.com/repos/userdocs/qbittorrent-nox-static/releases" | jq -r 'first(.[] | select(.tag_name | contains ("release-'"${{ needs.find-latest-version.outputs.qbt-version }}"_v1.2.'")) | .tag_name)')"

  update:
    runs-on: ubuntu-latest
    needs: find-latest-release
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: master
    - name: Create local changes
      run: |
        [ ! -z "$QBT_VERSION" ] && [[ "$QBT_VERSION" != "null" ]] && sed -i 's/.*ARG QBITTORRENT_RELEASE=.*/ARG QBITTORRENT_RELEASE="'${QBT_VERSION}'"/' Dockerfile
      env:
        QBT_VERSION: ${{ needs.find-latest-release.outputs.qbt-version }}
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update to ${{ needs.find-latest-release.outputs.qbt-version }}" -a || echo "Nothing to update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: master

  update-libtorrent1:
    runs-on: ubuntu-latest
    needs: find-latest-libtorrent1-release
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: libtorrent1
    - name: Create local changes
      run: |
        [ ! -z "$QBT_LIBTORRENT1_VERSION" ] && [[ "$QBT_LIBTORRENT1_VERSION" != "null" ]] && sed -i 's/.*ARG QBITTORRENT_RELEASE=.*/ARG QBITTORRENT_RELEASE="'${QBT_LIBTORRENT1_VERSION}'"/' Dockerfile
      env:
        QBT_LIBTORRENT1_VERSION: ${{ needs.find-latest-libtorrent1-release.outputs.qbt-libtorrent1-version }}
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update to ${{ needs.find-latest-libtorrent1-release.outputs.qbt-libtorrent1-version }}" -a || echo "Nothing to update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: libtorrent1
