#!/usr/bin/with-contenv sh

# Config folder
QB_CONFIG="${XDG_CONFIG_HOME}/qBittorrent"
# Config file
QB_CONFIG_FILE="${QB_CONFIG}/qBittorrent.conf"

# Folders
mkdir -p \
    "${QB_CONFIG}" \
    /config/log

# https://github.com/qbittorrent/qBittorrent/blob/master/src/base/settingsstorage.cpp
if [ ! -f "${QB_CONFIG_FILE}" ]; then
  echo "Initializing qBittorrent configuration..."
  cat > "${QB_CONFIG_FILE}" <<EOL
[Application]
FileLogger\Enabled=true
FileLogger\Path=/config/log

[BitTorrent]
Session\Port=54243
Session\DefaultSavePath=/downloads/torrents/qbittorrent/completed
Session\TempPath=/downloads/torrents/qbittorrent/incoming
Session\Preallocation=true

[Network]
PortForwardingEnabled=false
Proxy\OnlyForTorrents=false

[Preferences]
Connection\ResolvePeerCountries=false
General\Locale=en
WebUI\Address=*
WebUI\Port=8080
WebUI\LocalHostAuth=true
WebUI\UseUPnP=false
EOL
fi

# Permissions
chown -R abc:abc \
    /config
