#!/usr/bin/with-contenv sh

# Folders
mkdir -p \
    /config/.config/qBittorrent \
    /config/log

# https://github.com/qbittorrent/qBittorrent/blob/master/src/base/settingsstorage.cpp
if [ ! -f /config/.config/qBittorrent/qBittorrent.conf ]; then
  echo "Initializing qBittorrent configuration..."
  cat > /config/.config/qBittorrent/qBittorrent.conf <<EOL
[Application]
FileLogger\Enabled=true
FileLogger\Path=/config/log

[Preferences]
Connection\PortRangeMin=6881
Connection\ResolvePeerCountries=false
Connection\UPnP=false
Downloads\FinishedTorrentExportDir=/downloads/torrents
Downloads\PreAllocation=true
Downloads\SavePath=/downloads/incoming
General\Locale=en
General\UseRandomPort=false
WebUI\Address=*
WebUI\Port=8080
WebUI\LocalHostAuth=true
EOL
fi

# Permissions
chown -R abc:abc \
    /config
chown abc:abc \
    /downloads
